### ISSUE TITLE
Process registration not complete?

### ISSUE THREAD

**Issue by Daemach** [ddspringle/framework-one-secure-auth#14]
It looks like the process controller is truncated - what happens to the user object at this point and how is the view set?  https://github.com/ddspringle/framework-one-secure-auth/blob/master/home/controllers/main.cfc

**Comment by ddspringle** [comment]
Framework One (fw/1) is an MVC (Model, View, Controller) pattern that relies on convention over configuration. When 'process' is called it collects the registration data passed in the registration form, sets it into rc.userObj if it meets all required conditions, persists that user data back to the database with the userService.save() method and then fw/1 looks for and displays the 'process' view (https://github.com/ddspringle/framework-one-secure-auth/blob/master/home/views/main/process.cfm) automatically.

Carl has some great primers (and related presentations at conferences) on MVC basics. Have a look at this repo here: https://github.com/cfvonner/Intro-to-MVC-ColdFusion which might be a good place to start digging into ColdFusion MVC concepts.
