### ISSUE TITLE
Invalid Login Error

### ISSUE THREAD

**Issue by 41GitHub** [ddspringle/framework-one-secure-auth#17]
I'm totally new to FW1. I'm having this issue when entering an invalid login. 

Lucee (Gelert) Os 6.0.1.83 (CFML Version 2016,0,03,300357) Running with Commandbox

I login with an invalid login and it goes to 404 and then gets in an endless loop of 501 until browser stops it?

http://127.0.0.1:64073/fw1-sa/index.cfm?action=admin:main.authenticate
http://127.0.0.1:64073/fw1-sa/index.cfm?action=admin%3Amain.logout&msg=404
http://127.0.0.1:64073/fw1-sa/index.cfm?action=admin%3Amain.logout&msg=501
http://127.0.0.1:64073/fw1-sa/index.cfm?action=admin%3Amain.logout&msg=501
http://127.0.0.1:64073/fw1-sa/index.cfm?action=admin%3Amain.logout&msg=501
http://127.0.0.1:64073/fw1-sa/index.cfm?action=admin%3Amain.logout&msg=501
http://127.0.0.1:64073/fw1-sa/index.cfm?action=admin%3Amain.logout&msg=501

**Comment by ddspringle** [comment]
@41GitHub I found and resolved the issue with the infinite reload - the logout action was not listed among actions the security controller should not be run against, so every time it loaded it ran the security controller and thus, produced a 501. Please grab the latest code to get the fix. 

Great catch!
