### ISSUE TITLE
Typo in UserService.cfc - Line 99

### ISSUE THREAD

**Issue by SenatorCotton** [ddspringle/framework-one-secure-auth#8]
Typo in model/services/UserService.cfc - Line 99
ending '.' (period) should be ',' (comma).

This assumes I'm looking at the most recent version and not an idiot. I must add, a lot of your code makes me feel like an idiot. Thanks and nicely done.

![typo-userservice cfc](https://user-images.githubusercontent.com/10125486/41196087-e4e40f7a-6c06-11e8-8ccb-d9085ebe7e00.png)

**Comment by ddspringle** [comment]
Doh! Nice catch! Thank you :)
